import static org.junit.jupiter.api.Assertions.*;

// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.interactions.Actions;

import java.util.HashMap;
import java.util.Map;

public class L10P2Test {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        driver = new FirefoxDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
        System.setProperty("webdriver.chrome.driver", "/Users/miablo/Downloads/chromedriver.exe");
        driver = new ChromeDriver();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void l10P2() {
        driver.get("https://docs.oracle.com/javase/9/docs/api/overview-summary.html");
        driver.manage().window().setSize(new Dimension(680, 758));
        driver.findElement(By.id("search")).click();
        driver.findElement(By.cssSelector("#ui-id-4426 .resultHighlight")).click();
        driver.findElement(By.cssSelector(".rowColor:nth-child(3) > .colConstructorName a")).click();
        driver.findElement(By.id("search")).click();
        {
            WebElement element = driver.findElement(By.cssSelector("#ui-id-8115 .resultHighlight"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        {
            WebElement element = driver.findElement(By.cssSelector("#ui-id-8116 .resultHighlight"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        driver.findElement(By.cssSelector("#ui-id-8116 .resultHighlight")).click();
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
        driver.findElement(By.cssSelector(".altColor:nth-child(4) > .colConstructorName .memberNameLink > a")).click();
    }
}
